name: Release - Generate App Bundle New

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release AAB
        run: ./gradlew bundleRelease

#      - name: List Contents of Directory
#        run: ls -R app/build/outputs/bundle/release/
#
#      - name: Print File Permissions
#        run: ls -l app/build/outputs/bundle/release/

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks

      - name: Sign App Bundle
        run: |
          key_alias=${{ secrets.KEY_ALIAS }}
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore keystore.jks -storepass ${{ secrets.KEYSTORE_PASSWORD }} -keypass ${{ secrets.KEY_PASSWORD }} -signedjar app-release-signed.aab app/build/outputs/bundle/release/app-release.aab $key_alias

      - name: Upload Bundle
        uses: actions/upload-artifact@v3
        with:
          name: app-release-signed
          path: app-release-signed.aab
