name: Release - Generate APK 2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3.2.0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks

      - name: Build Release APK
        env:
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          RELEASE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          RELEASE_KEYSTORE_ALIAS: ${{ secrets.KEY_ALIAS }}

        run: ./gradlew assembleRelease --stacktrace

      - name: Find APK file
        id: findApk
        run: echo "::set-output name=apk_path::$(find app/build/outputs/apk/release -name '*.apk' -print -quit)"

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: ${{ steps.findApk.outputs.apk_path }}