name: Release - Generate APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3.2.0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks

      - name: Zipalign APK
        run: zipalign -v 4 app/build/outputs/apk/release/app-release-unsigned.apk app-release-aligned.apk

      - name: Sign APK
        run: |
          apksigner sign --ks keystore.jks --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} --key-pass pass:${{ secrets.KEY_PASSWORD }} --out app-release-signed.apk app-release-aligned.apk

      - name: Verify APK Signature
        run: |
          apksigner verify app-release-signed.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-signed-apk
          path: app-release-signed.apk