name: Release - Generate APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks

#      - name: Sign APK
#        run: |
#          key_alias=${{ secrets.KEY_ALIAS }}
#          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore keystore.jks -storepass ${{ secrets.KEYSTORE_PASSWORD }} -keypass ${{ secrets.KEY_PASSWORD }} -signedjar app-release-signed.apk app/build/outputs/apk/release/app-release-unsigned.apk $key_alias
#
#      - name: Upload APK
#        uses: actions/upload-artifact@v4
#        with:
#          name: app-release-signed-apk
#          path: app-release-signed.apk

      - name: Zipalign APK
        run: zipalign -v 4 app/build/outputs/apk/release/app-release-unsigned.apk app-release-aligned.apk

      - name: Sign APK
        run: |
          apksigner sign --ks keystore.jks --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} --key-pass pass:${{ secrets.KEY_PASSWORD }} --out app-release-signed.apk app-release-aligned.apk

      - name: Verify APK Signature
        run: |
          apksigner verify app-release-signed.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-signed-apk
          path: app-release-signed.apk